import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import"./style.css";

const phases=[
 [0,"First Day","Learn the basics, gather supplies and survive your first night."],
 [1,"Foundation","Food, iron, tools and a safe home."],[2,"Founding","Scout and choose the capital site."],
 [3,"Settlement","Storage, farms, homes and basic defenses."],[4,"Population","Bring villagers home and start a real population."],
 [5,"Town","Market, roads, professions and a town square."],[6,"Royal","Castle, walls, gates and civic buildings."],
 [7,"Economy","Trading, enchanted gear and production."],[8,"Infrastructure","Roads, bridges, boats, rail and maps."],
 [9,"Expansion","Found and connect a second settlement."],[10,"Power","Nether, enchanting and advanced production."],
 [11,"Kingdom","Landmarks, decoration, stories and celebration."]
];

const missions=[
 {id:"wood",phase:0,title:"Gather wood",summary:"Collect enough logs to make your first tools and a starter camp.",time:"10–15 min",need:["16+ logs","Crafting table","Axe"],steps:["Punch or chop nearby trees until you have at least 16 logs each.","Turn some logs into planks and sticks.","Craft a crafting table and wooden axe. Keep extra logs for fuel and building.","Don't strip every tree around camp — leave a few so the area stays useful."],why:"Wood is the universal early-game material. Getting a little extra now prevents repeated trips later.",tips:["Spruce, oak and birch all work. Pick one local wood as the kingdom's early building style.","Keep one stack of logs in shared storage."],unlocks:"Stone tools"},
 {id:"stone",phase:0,title:"Upgrade to stone tools",summary:"Replace wooden tools with a stone pickaxe, axe, sword and shovel.",time:"10 min",need:["20+ cobblestone","Crafting table","Sticks"],steps:["Find exposed stone or dig a shallow staircase into a hill.","Mine cobblestone with the wooden pickaxe.","Craft a stone pickaxe first, then axe, sword and shovel.","Keep the wooden pickaxe only for emergencies; don't waste time repairing it."],why:"Stone tools are dramatically faster and unlock iron mining.",tips:["Carry a few spare sticks in the hotbar.","A furnace is worth crafting immediately after tools."],unlocks:"Renewable food"},
 {id:"food",phase:1,title:"Secure renewable food",summary:"Start one crop and one animal source so food stops being a constant problem.",time:"20–30 min",need:["Hoe","Seeds or village crops","Water source","Animal pair if possible"],steps:["Choose a flat patch close to camp.","Put water in or beside the field and till the nearby dirt.","Plant wheat, carrots or potatoes. Replant every harvest.","If you find cows or sheep, fence two animals and feed them to breed.","Put a chest beside the farm for seeds and spare food."],why:"A renewable food loop makes exploration, mining and villager work much easier.",tips:["Wheat is especially useful later because villagers and cows can both use it.","Don't make the farm huge yet. A compact starter farm is enough."],unlocks:"First-night shelter"},
 {id:"night",phase:1,title:"Survive the first night",summary:"Make a safe, lit sleeping spot and avoid spending the whole night fighting mobs.",time:"15–25 min",need:["Bed","Torches","Food","Door or blocks"],steps:["Build a tiny shelter near your food and storage.","Place torches inside and around the entrance.","Craft a bed and sleep when possible.","Make a small fenced area or wall around anything important.","Keep a spare bed and food ready for the next night."],why:"The goal of the first night is not a beautiful house. It is to create a safe reset point.",tips:["An ugly dirt box is a successful first house.","Never leave valuables in an unlit open area."],unlocks:"Capital scouting"},
 {id:"scout",phase:2,title:"Scout three capital sites",summary:"Find three promising locations before committing the kingdom to one spot.",time:"30–60 min",need:["Food","Bed","Boat if useful","Lots of blocks"],steps:["Travel in a wide loop instead of walking randomly.","For each candidate, check water, trees, food, terrain and room to expand.","Look for a memorable natural feature: hill, river bend, cliff, lake or coast.","Take a screenshot and write down coordinates for all three.","Score each site out of 5 for scenery, resources, defense and building space."],why:"Moving a capital after building it is painful. A short scouting phase saves hours.",tips:["A river or coast makes the capital feel connected to the world.","Don't choose only for looks — nearby food and wood matter too."],unlocks:"Choose the capital"},
 {id:"capital",phase:2,title:"Choose the capital",summary:"Pick one site, enable coordinates and record the kingdom's starting point.",time:"10 min",need:["Chosen site","Coordinates enabled","Sign or map marker"],steps:["Stand at the approximate center of the future town square.","Record X/Y/Z in Royal Coordinates.","Place a temporary marker such as a tall pillar or campfire.","Agree that this is the capital before making major permanent builds.","Create a screenshot from a high point so you remember the landscape."],why:"This is the moment your survival world becomes a planned kingdom.",tips:["The town square should have room to grow around it.","Leave at least one side open for a future road, harbor or district."],unlocks:"Storage hall"},
 {id:"storage",phase:3,title:"Build the storage hall",summary:"Create one shared, labeled storage room before the kingdom starts accumulating junk.",time:"20–40 min",need:["Wood","Chests","Signs or item frames","Building blocks"],steps:["Build close to the temporary base and future town center.","Make separate rows for building blocks, ores, food, farming, tools and valuables.","Label every row. Keep a 'SORT ME' chest for items you don't have time to organize.","Put the most-used materials near the entrance.","Leave empty space for future expansion."],why:"Shared storage is the foundation of a two-player world. Both players should know where things go.",tips:["Use double chests rather than dozens of single chests.","A dedicated valuables chest saves accidental losses."],unlocks:"Starter farms"},
 {id:"farms",phase:3,title:"Build starter farms",summary:"Make compact crop and animal farms that can feed both players and future villagers.",time:"30–45 min",need:["Seeds","Water","Fence or walls","Wheat or other animal food"],steps:["Finish the main crop field near storage.","Build a cow/sheep pen with two animals to start breeding.","Add a sugar-cane strip beside water if you have found some.","Place a chest near each farm for seeds, breeding food and tools.","Make paths between farms so the district can later become the agricultural quarter."],why:"The farms you build now become the first production district of the capital.",tips:["Keep farms compact and tidy; they will later be expanded into a district.","Sugar cane is worth starting early because paper becomes important for books and maps."],unlocks:"Villager transport"},
 {id:"villagers",phase:4,title:"Bring villagers home",summary:"Safely move at least two villagers from a village to the capital.",time:"30–60 min",need:["Boat or minecart","Beds","Food","Blocks for a safe room"],steps:["Find a village and identify two villagers you want to transport.","Build a temporary secure room at the destination before moving them.","Use a boat for simple overland/water transport, or rails later if the route is long.","Protect the villagers from zombies, falls and wandering away.","Place beds and keep the room well lit."],why:"Villagers turn the capital from a decorative settlement into an economy.",tips:["Move only two at first. Learn the system before building a giant trading hall.","Keep villagers protected before worrying about perfect trades."],unlocks:"Villager breeding"},
 {id:"breeder",phase:4,title:"Start population",summary:"Give your villagers food and enough spare valid beds to produce your first baby villagers.",time:"20–40 min",need:["2 adult villagers","Spare beds","Carrots, potatoes or bread","Safe enclosed area"],steps:["Put two adults in a safe breeding area.","Place more beds than the current population; leave clear space above each bed.","Give the adults enough food to become willing to breed.","Wait for hearts and a baby villager.","Move the baby into the wider village area once it is safe."],why:"Population is the gateway to professions, trading and eventually a full town.",tips:["If breeding fails, check food, bed count and whether the beds can actually be reached.","Don't turn the first villagers into a complicated trading hall immediately."],unlocks:"Town square"},
 {id:"square",phase:5,title:"Build the town square",summary:"Create the social heart of the capital: roads, lighting, a gathering space and a landmark.",time:"45–90 min",need:["Road material","Lanterns/torches","Stone or wood","Central landmark"],steps:["Mark a roughly square or circular plaza around your chosen center coordinates.","Build the main road through or around it.","Add a well, fountain, tree, statue or other focal point.","Place lighting so the square is safe at night.","Leave four obvious exits for future districts."],why:"The square gives every later building a relationship to the capital instead of becoming a pile of unrelated houses.",tips:["Keep the center visually open.","Use one main road material and one accent block for consistency."],unlocks:"Market"},
 {id:"market",phase:5,title:"Open the market",summary:"Turn the first villager jobs into a visible commercial district.",time:"45–75 min",need:["Villagers","Workstations","Building blocks","Beds nearby"],steps:["Choose a small group of villagers to become your first specialists.","Give farmers, librarians or other useful villagers their workstations.","Build individual stalls or tiny shops rather than a giant box.","Keep the trading area close to the town square.","Record particularly useful trades so you know which villagers to protect."],why:"A market makes the economy feel like part of the city and gives your villagers a purpose in the build.",tips:["Librarians can become a long-term priority for enchanted books.","Don't overcrowd the first market. Expand it as the population grows."],unlocks:"Castle layout"},
 {id:"castle",phase:6,title:"Lay out the castle",summary:"Mark the footprint and foundation of the future royal castle before decorating it.",time:"60–120 min",need:["Stone/deepslate","Wood accent","Building plan","Large clear area"],steps:["Choose a prominent point overlooking the town.","Mark the outer footprint with cheap blocks first.","Decide where the gate, keep, courtyard and towers will go.","Build only the foundation and main vertical masses first.","Walk around it from the town square and check the silhouette before detailing."],why:"A castle is much easier to improve when the proportions are solved before the walls are covered in detail.",tips:["Build the silhouette first, windows and decoration later.","A smaller castle with a strong shape looks better than an enormous unfinished one."],unlocks:"Capital defenses"},
 {id:"walls",phase:6,title:"Defend the capital",summary:"Build a recognizable gate, perimeter wall and two watchtowers.",time:"60–120 min",need:["Stone/brick","Torches or lanterns","Gate materials","Stairs/slabs"],steps:["Decide what part of the settlement needs to be inside the first wall.","Run the wall around districts rather than every individual house.","Make one main gate aligned with the primary road.","Add two towers at meaningful corners or gate approaches.","Light the wall walk and entrances."],why:"The first wall establishes the capital's identity and gives you a clear boundary for future expansion.",tips:["Don't wall off your farms so tightly that there is no room to expand.","Use towers to create visual landmarks, not just decoration."],unlocks:"Trading hall"},
 {id:"trading",phase:7,title:"Start the trading hall",summary:"Build a compact, organized trading area and begin collecting useful trades.",time:"60–120 min",need:["Villagers","Workstations","Beds if needed","Food/emeralds"],steps:["Choose a safe building close to the market district.","Separate villagers into small stalls or rooms.","Start with farmers for food/emerald flow and librarians for books.","Add armorer, toolsmith and weaponsmith as resources allow.","Record your best trades in the villager notes or a project card."],why:"Trading converts renewable farm output into tools, gear, building blocks and eventually powerful enchantments.",tips:["Protect important villagers before doing anything risky.","Keep the hall expandable instead of building 30 stalls immediately."],unlocks:"Kingdom road"},
 {id:"road",phase:8,title:"Connect the kingdom",summary:"Build a proper route from the capital to one useful destination.",time:"30–90 min",need:["Road blocks","Torches/lanterns","Signs","Boat/rail materials if needed"],steps:["Choose one destination: village, mine, farm, harbor or outpost.","Mark the route before decorating it.","Use a consistent road palette and regular lighting.","Add signs at forks and important destinations.","Make a safe bridge or boat crossing where necessary."],why:"A kingdom feels connected when travel has infrastructure instead of random dirt paths.",tips:["Roads should be useful first and beautiful second.","Use a repeating lamp/sign rhythm to make long roads readable."],unlocks:"Territory map"},
 {id:"map",phase:8,title:"Map the territory",summary:"Explore the area around the capital and turn important places into a shared reference.",time:"45–90 min",need:["Map(s)","Food","Boat if useful","Coordinates"],steps:["Explore north, south, east and west from the capital over multiple trips.","Record villages, biomes, mines, structures, rivers and scenic sites.","Create a wall map later, but keep coordinates as the reliable reference.","Mark dangerous or valuable areas before forgetting them.","Choose one future expansion direction."],why:"Mapping changes exploration from wandering into strategic planning.",tips:["Name places as you discover them — names become part of the kingdom's story.","Don't carry all valuables while mapping."],unlocks:"Second settlement"},
 {id:"outpost",phase:9,title:"Found settlement two",summary:"Choose a distinct biome and establish a small satellite outpost.",time:"60–120 min",need:["Bed","Food","Starter tools","Building blocks","Coordinates"],steps:["Pick a location with a reason to exist: resources, biome, coast, mountain or trade route.","Build a tiny safe core: bed, storage, food and lighting.","Add a local landmark so the settlement has an identity.","Record its coordinates and give it a name.","Plan one route back to the capital."],why:"The second settlement proves the kingdom is becoming a network rather than one city.",tips:["Don't build another capital. Give the outpost a specialized purpose.","Different wood or stone palettes can make each region feel distinct."],unlocks:"Connect settlements"},
 {id:"connect",phase:9,title:"Connect both settlements",summary:"Build a road, bridge, boat route or rail connection between the two settlements.",time:"60–180 min",need:["Chosen transport materials","Signs","Lighting","Food"],steps:["Scout the safest practical route.","Build the main path first without decoration.","Solve rivers, cliffs and hostile areas with bridges or alternate routes.","Add signs at the capital and outpost ends.","Decorate the route after travel is reliable."],why:"Infrastructure is what makes two settlements part of one kingdom.",tips:["If the distance is huge, a boat route can be the simplest early solution.","Rail can wait until the kingdom has a reason to justify the materials."],unlocks:"Nether gateway"},
 {id:"nether",phase:10,title:"Build the Nether gateway",summary:"Create a safe portal room and establish a reliable return route.",time:"30–90 min",need:["Obsidian","Flint and steel","Blocks","Food","Gold if exploring"],steps:["Build the portal in a protected room rather than in the middle of town.","Light it and make the entrance safe from accidental falls or mobs.","Record the Overworld coordinates before entering.","In the Nether, secure the portal with a small shelter and a visible path.","Record both sides so the route can be expanded later."],why:"The Nether becomes a fast-travel network and opens access to materials needed for the late kingdom.",tips:["Bring cheap blocks for emergency bridges.","Never enter with your entire best inventory."],unlocks:"Enchanting"},
 {id:"enchant",phase:10,title:"Build enchanting",summary:"Create an enchanting room and start turning good gear into great gear.",time:"45–90 min",need:["Enchanting table","Bookshelves","Lapis lazuli","Experience"],steps:["Build a dedicated enchanting room near storage or the castle.","Gather books and bookshelves as your sugar cane and leather production grows.","Arrange the bookshelves around the table with a clear gap so the setup can reach higher enchantment levels.","Keep lapis and repairable gear nearby.","Use the room as a long-term equipment upgrade station."],why:"Enchanting is the point where survival gear starts becoming kingdom-grade equipment.",tips:["Don't spend rare resources on every early tool; save strong enchantments for gear you expect to keep.","Combine useful books at an anvil when appropriate."],unlocks:"Kingdom feast"},
 {id:"feast",phase:11,title:"Hold the kingdom feast",summary:"Finish one landmark, decorate the square and celebrate the kingdom's first major milestone.",time:"60+ min",need:["Food","Decorations","Completed landmark","All players"],steps:["Choose one landmark to finish: castle exterior, fountain, gate, harbor or monument.","Clean up temporary dirt towers, chests and unfinished paths around the square.","Add banners, lanterns, seating, tables or stalls.","Prepare a chest of food and invite both players to the square.","Take a screenshot and give the capital a proper name."],why:"A long survival project needs milestones. The feast turns progress into a shared memory.",tips:["Take a screenshot from the same viewpoint each major phase.","Write down the funniest disaster from the journey — it becomes kingdom lore."],unlocks:"Free-build kingdom mode"}
];

const resources=[
 ["🌲","Wood","Trees → logs → planks","Building, tools and fuel."],["🪨","Stone","Mine exposed stone/cobblestone with a pickaxe","Tools, furnaces, roads and buildings."],["⚫","Coal","Coal ore or charcoal from logs","Torches and furnace fuel."],["⚙️","Iron","Mine iron ore; later automate it","Buckets, shields, tools, armor and machines."],["💎","Diamonds","Deep underground; modern worlds commonly find them around the deep slate layers","High-tier gear and enchanting infrastructure."],["🌾","Crops","Seeds from grass; carrots/potatoes can come from villages","Food and villager breeding."],["🍬","Sugar Cane","Grow beside water","Paper, books and maps."],["🐄","Leather","Cows + breeding","Books and item frames."],["🧵","Wool","Sheep + shears/breeding","Beds and decoration."],["🟢","Emeralds","Villager trading","Kingdom currency."],["📚","Enchanted Books","Librarian trades or enchanting","Powerful equipment upgrades."]
];

const learn=[
 ["🧭 Survival loop","Explore → collect → craft → build → upgrade → automate. Survival has no required story route; the campaign is the structure we are adding on top.",["A good session always has a purpose: gather, build, explore or unlock.","Don't overbuild before you have food and storage."]],
 ["🎒 Inventory & storage","Your inventory is your backpack and the hotbar is your immediate toolkit. Chests are shared memory for the kingdom.",["Keep food, blocks, pickaxe, axe and torches accessible.","Create a SORT ME chest so clutter does not spread through every chest."]],
 ["⛏️ Mining safely","Pickaxe mines stone and ores. Bring food, torches, blocks and a shield. Light every area you enter.",["Never dig straight down or straight up.","If you hear lava, slow down and open a controlled route.","Mark your route back instead of trusting memory."]],
 ["🌾 Farming","Crops need hydrated farmland and light. Replant after harvesting and keep animal breeding pairs separate from the main pen when possible.",["Wheat is useful because it feeds cows and can be used for villager breeding indirectly through bread.","Sugar cane is a long-term paper source."]],
 ["🧑‍🌾 Villagers","A villager economy starts with safe housing, beds, food and workstations. Professions turn ordinary resources into useful trades.",["Librarian = books, Farmer = food/emerald loop, Armorer = armor, Toolsmith = tools, Weaponsmith = weapons, Fletcher = arrows/emeralds, Mason = building blocks.","Protect important villagers before experimenting with risky transport or combat."]],
 ["⚔️ Combat basics","Shield incoming attacks, fight from controlled positions and use the environment instead of charging into dark caves.",["Keep your hunger high enough to regenerate when possible.","If a fight gets bad, retreat behind blocks and reset the situation."]],
 ["🧭 Coordinates","In Bedrock, X/Z describe horizontal position and Y is elevation. Record the capital, villages, mines, outposts and portals.",["Use signs in-world and Royal Coordinates in HQ.","Coordinates are more reliable than screenshots alone."]],
 ["🌋 Nether survival","Treat the Nether like a dangerous transport network, not a casual sightseeing trip.",["Carry cheap blocks for bridges and emergency walls.","Protect portal entrances and record both sides of important routes."]]
];

const mapZones=[
 {id:"castle",icon:"🏰",name:"Royal Castle",x:43,y:7,desc:"The visual and administrative heart of the kingdom.",build:"Keep, throne room, map room, treasury and armory.",phase:6,links:["Town Square","Defensive Wall"]},
 {id:"square",icon:"🏛️",name:"Town Square",x:40,y:43,desc:"The central public space where the main roads meet.",build:"Plaza, fountain/well, lamps, banners and civic landmark.",phase:5,links:["Market","Residential"]},
 {id:"homes",icon:"🏠",name:"Residential District",x:6,y:58,desc:"A neighborhood for players and later villagers.",build:"Small houses, tavern, gardens and paths.",phase:5,links:["Town Square","Market"]},
 {id:"farms",icon:"🌾",name:"Agricultural Quarter",x:5,y:12,desc:"Food production and the future rural edge of the capital.",build:"Crop fields, barn, animal pens and sugar cane.",phase:3,links:["Storage Hall","Residential"]},
 {id:"industry",icon:"⚒️",name:"Industry & Storage",x:73,y:53,desc:"The practical working district where resources are processed.",build:"Storage hall, furnaces, workshops and later automated farms.",phase:3,links:["Market","Harbor"]},
 {id:"harbor",icon:"⚓",name:"Harbor",x:72,y:12,desc:"A future gateway for boats, trade and coastal expansion.",build:"Docks, warehouse, lighthouse and road connection.",phase:8,links:["Industry","Town Square"]},
 {id:"market",icon:"🧺",name:"Market Street",x:70,y:39,desc:"Visible shops and villager professions around the town center.",build:"Stalls, librarian shop, farmer, smiths and tavern frontage.",phase:5,links:["Town Square","Industry"]},
 {id:"wall",icon:"🛡️",name:"Defensive Wall",x:15,y:80,desc:"The first clear boundary of the capital.",build:"Gate, wall walk and watchtowers.",phase:6,links:["Castle","Residential"]}
];

const roles=[["⛏️","Engineer / Explorer","Mining, mapping, exploration, transport and practical infrastructure."],["🏗️","Architect / Steward","Farms, decoration, homes, villagers and district planning."]];
const LS="kingdomHQ.v3";
function load(){try{return JSON.parse(localStorage.getItem(LS))||JSON.parse(localStorage.getItem("kingdomHQ.v2"))||{}}catch{return {}}}

function App(){
 const initial=load();
 const [s,setS]=useState(()=>Object.assign({done:[],phase:0,projects:[],coords:[],builds:[],session:""},initial));
 const [tab,setTab]=useState("hq"); const [selected,setSelected]=useState(null); const [learnOpen,setLearnOpen]=useState(null);
 useEffect(()=>localStorage.setItem(LS,JSON.stringify(s)),[s]);
 const completed=useMemo(()=>new Set(s.done),[s.done]);
 const unlocked=m=>m.phase===0||m.needUnlock===true||m.prereq?.every(id=>completed.has(id));
 const missionById=id=>missions.find(m=>m.id===id);
 const available=missions.filter(m=>!completed.has(m.id)&&(!m.prereq||m.prereq.every(id=>completed.has(id))));
 const current=available[0]||missions.find(m=>!completed.has(m.id))||missions.at(-1);
 const pct=Math.round(completed.size/missions.length*100);
 const phaseDone=missions.filter(m=>m.phase===s.phase&&completed.has(m.id)).length;
 const phaseTotal=missions.filter(m=>m.phase===s.phase).length;
 const save=x=>setS(x);
 const complete=id=>save({...s,done:[...new Set([...s.done,id])]});
 const toggle=id=>completed.has(id)?save({...s,done:s.done.filter(x=>x!==id)}):complete(id);
 const phaseMissions=missions.filter(m=>m.phase===s.phase);
 const nextForPhase=phaseMissions.find(m=>!completed.has(m.id));
 const openMission=m=>setSelected({type:"mission",item:m});
 const random=["Build a lookout on the nearest hill.","Make a tiny bridge somewhere useful.","Create a cozy two-player picnic spot.","Find a new biome and bring home a souvenir.","Build a public well in the town square.","Create a hidden royal treasure room.","Make a road sign pointing home.","Find a scenic place for the future palace."];
 const newSide=()=>save({...s,session:random[Math.floor(Math.random()*random.length)]});
 return <div className="app">
  <header><div className="eyebrow">TWO PLAYERS • ONE WORLD</div><h1>🏰 Kingdom HQ</h1><p>Your Bedrock survival campaign manager.</p><div className="hero"><div><span className="label">PHASE {phases[s.phase][0]}</span><h2>{phases[s.phase][1]}</h2><p>{phases[s.phase][2]}</p></div><strong>{pct}%</strong><div className="progress"><i style={{width:pct+"%"}}/></div></div></header>
  <nav>{[["hq","🏰","HQ"],["play","🎮","Play"],["learn","📖","Learn"],["build","🗺️","Build"],["more","📋","More"]].map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}><b>{x[1]}</b>{x[2]}</button>)}</nav>
  <main>
   {tab==="hq"&&<>
    <Card title="🎯 What you should do next"><button className="missionHero" onClick={()=>openMission(current)}><div><span className="kicker">PHASE {current.phase} • {current.time}</span><h3>{current.title}</h3><p>{current.summary}</p></div><span className="arrow">›</span></button><div className="chips"><span className="chip ok">{completed.has(current.id)?"DONE":"NEXT UP"}</span><span className="chip">{current.need?.length||0} prep items</span></div><button className="primary" onClick={()=>openMission(current)}>Open step-by-step guide →</button></Card>
    <Card title="🧭 Campaign"><div className="phaseScroll">{phases.map((p,i)=><button key={i} className={i===s.phase?"phase active":i<s.phase?"phase done":"phase"} onClick={()=>save({...s,phase:i})}><small>{p[0]}</small><b>{p[1]}</b></button>)}</div><p className="small">Phase {s.phase}: {phaseDone}/{phaseTotal} objectives complete.</p></Card>
    <Card title="📞 Two-player call cheat-sheet"><div className="callgrid"><div><b>Give the builder</b><span>“Make the farm 9×9 and put the chest beside it.”</span></div><div><b>Give the explorer</b><span>“Find a village and record its coordinates.”</span></div><div><b>Regroup</b><span>“Meet at the town square when you're done.”</span></div></div></Card>
    <div className="grid">{roles.map(r=><div className="tile" key={r[1]}><b>{r[0]} {r[1]}</b><span>{r[2]}</span></div>)}</div>
   </>}

   {tab==="play"&&<>
    <Card title="🎮 Tonight's session"><div className="sessionTop"><select value={s.phase} onChange={e=>save({...s,phase:+e.target.value})}>{phases.map(p=><option key={p[0]} value={p[0]}>Phase {p[0]} — {p[1]}</option>)}</select><span>{phaseDone}/{phaseTotal} done</span></div>{phaseMissions.map(m=><button className="missionRow" key={m.id} onClick={()=>openMission(m)}><span className={completed.has(m.id)?"circle checked":"circle"}>{completed.has(m.id)?"✓":""}</span><span><b>{m.title}</b><small>{m.summary}</small></span><em>›</em></button>)}</Card>
    <Card title="🎲 Side quest"><div className="side">{s.session||"Need a fun 10-minute job while the other player mines? Generate one."}</div><button onClick={newSide}>🎲 Generate another</button></Card>
   </>}

   {tab==="learn"&&<><Card title="📖 Minecraft 101"><p className="intro">Open a topic when you need an answer during the call. These are practical rules, not a wall of theory.</p>{learn.map((x,i)=><button className="learnRow" key={x[0]} onClick={()=>setLearnOpen(learnOpen===i?null:i)}><div><b>{x[0]}</b><span>{x[1]}</span></div><strong>{learnOpen===i?"−":"+"}</strong>{learnOpen===i&&<div className="learnDetail">{x[2].map(t=><p key={t}>• {t}</p>)}</div>}</button>)}</Card><Card title="🎒 Starter loadout"><div className="grid">{["🪓 Axe","⛏️ Pickaxe","🗡️ Sword","🪣 Bucket","🍖 Food","🔥 Torches","🧱 Blocks","🛏️ Bed"].map(x=><div className="tile compact" key={x}>{x}</div>)}</div></Card></>}

   {tab==="build"&&<>
    <Card title="🗺️ Interactive capital map"><p className="intro">Tap any district. The map is a planning board now — each zone explains its purpose, build stage and neighbors.</p><div className="map">{mapZones.map(z=><button key={z.id} className="zone" style={{left:z.x+"%",top:z.y+"%"}} onClick={()=>setSelected({type:"zone",item:z})}><span>{z.icon}</span><b>{z.name}</b></button>)}<div className="river r1"/><div className="river r2"/><div className="road road1"/><div className="road road2"/></div></Card>
    <Card title="🏗️ Build order"><p className="intro">Do the big shapes first. Details come after the settlement works.</p>{["Central road + town square","Two houses","Storage hall","Crop fields + barn","Animal pens","Villager quarter","Market street","Defensive wall + gate","Castle foundation","Castle keep","Harbor + warehouse","Grand monument"].map((x,i)=><Check key={x} checked={s.builds.includes(i)} text={(i+1)+". "+x} on={()=>save({...s,builds:s.builds.includes(i)?s.builds.filter(v=>v!==i):[...s.builds,i]})}/>)}</Card>
    <Card title="🏘️ District quick guide"><div className="grid">{mapZones.map(z=><button className="tile clickable" key={z.id} onClick={()=>setSelected({type:"zone",item:z})}><b>{z.icon} {z.name}</b><span>Build from Phase {z.phase}</span></button>)}</div></Card>
   </>}

   {tab==="more"&&<><Card title="🧑‍🌾 Villager civilization"><div className="flow">🚣 Find → 🏠 Transport → 🛏️ Beds → 🥕 Food → 👶 Breed → 💼 Jobs → 💰 Trade</div><p className="small">Start with two villagers. Protect them first; optimize trades second.</p><table><tbody>{[["📚 Librarian","Lectern","Books"],["🌾 Farmer","Composter","Food + emeralds"],["🛡️ Armorer","Blast Furnace","Armor"],["⛏️ Toolsmith","Smithing Table","Tools"],["⚔️ Weaponsmith","Grindstone","Weapons"],["🏹 Fletcher","Fletching Table","Arrows + emeralds"],["🧱 Mason","Stonecutter","Building blocks"]].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></Card><Card title="⛏️ Resource guide">{resources.map(r=><div className="resource" key={r[1]}><span className="ico">{r[0]}</span><div><b>{r[1]}</b><span>{r[2]}</span><small>{r[3]}</small></div></div>)}</Card><Card title="📋 Your projects"><div className="add"><input id="newProject" placeholder="e.g. Build the western gate"/><button onClick={()=>{let v=document.getElementById("newProject")?.value.trim();if(v)save({...s,projects:[...s.projects,{text:v,done:false}]})}}>Add</button></div>{s.projects.map((p,i)=><Check key={i} checked={p.done} text={p.text} on={()=>{let a=[...s.projects];a[i].done=!a[i].done;save({...s,projects:a})}}/>)}</Card><Card title="📍 Royal coordinates"><div className="add"><input id="coordN" placeholder="Capital / village / mine"/><input id="coordV" placeholder="X / Y / Z"/><button onClick={()=>{let n=document.getElementById("coordN")?.value.trim(),v=document.getElementById("coordV")?.value.trim();if(n&&v)save({...s,coords:[...s.coords,{n,v}]})}}>Save</button></div>{s.coords.map((c,i)=><div className="coord" key={i}><b>{c.n}</b><span>{c.v}</span><button onClick={()=>save({...s,coords:s.coords.filter((_,j)=>j!==i)})}>×</button></div>)}</Card><Card title="⚠️ Reset campaign"><p className="small">Deletes this device's saved Kingdom HQ progress.</p><button className="danger" onClick={()=>{if(confirm("Reset all Kingdom HQ progress?")){localStorage.removeItem(LS);location.reload()}}}>Reset</button></Card></>}
  </main>
  {selected&&<Modal item={selected} completed={completed} onClose={()=>setSelected(null)} onComplete={complete} />}
 </div>
}

function Modal({item,completed,onClose,onComplete}){const isMission=item.type==="mission"; const x=item.item; return <div className="overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button>{isMission?<><span className="kicker">PHASE {x.phase} • {x.time}</span><h2>{x.title}</h2><p className="modalSummary">{x.summary}</p><h3>🎒 Before you start</h3><div className="needgrid">{x.need.map(n=><span key={n}>{n}</span>)}</div><h3>🧭 Do it like this</h3><ol>{x.steps.map(t=><li key={t}>{t}</li>)}</ol><div className="why"><b>Why it matters</b><p>{x.why}</p></div><h3>💡 Two-player tips</h3><ul>{x.tips.map(t=><li key={t}>{t}</li>)}</ul><div className="unlock"><b>Next unlock</b><span>→ {x.unlocks}</span></div><button className="primary" onClick={()=>{onComplete(x.id);onClose()}}>{completed.has(x.id)?"✓ Completed":"✓ Mark objective complete"}</button></>:<><span className="kicker">CAPITAL DISTRICT • PHASE {x.phase}</span><h2>{x.icon} {x.name}</h2><p className="modalSummary">{x.desc}</p><h3>🏗️ What goes here</h3><p>{x.build}</p><h3>🔗 Connects to</h3><div className="chips">{x.links.map(l=><span className="chip" key={l}>{l}</span>)}</div><div className="why"><b>Planning rule</b><p>Build the useful core first, then let decoration grow around it. Leave clear roads and expansion space.</p></div><button className="primary" onClick={onClose}>Got it</button></>}</div></div>}
function Card({title,children}){return <section className="card"><h2>{title}</h2>{children}</section>}
function Check({checked,text,sub,on}){return <label className={"check "+(checked?"done":"")}><input type="checkbox" checked={checked} onChange={on}/><span><b>{text}</b>{sub&&<small>{sub}</small>}</span></label>}
createRoot(document.getElementById("root")).render(<App/>);
